#!/bin/csh
echo Enter a number between 1 and 10
@ input = $<
if ( $input < 1 || $input > 10 ) then
 echo not a valid range, must be between 1 and 10
 exit
endif

@ sum = ( $input * ( $input + 1 ) ) / 2
echo Sum is $sum

@ mult = 1
@ i = 1
while ( $i <= $input )
 @ mult = $mult * $i
 @ i = $i + 1
end

echo factorial is $mult
